apiVersion: v1
kind: Namespace
metadata:
  name: boost-sales-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boost-sales-pod # Base POD name
  namespace: boost-sales-system
spec:
  selector:
    matchLabels:
      app: boost-sales # Selector for POD name search.
  template:
    metadata:
      labels:
        app: boost-sales
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
      - name: boost-sales-api
        image: bersennaidoo/boost-sales-api
