apiVersion: v1
kind: Namespace
metadata:
  name: boost-sales-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boost-sales-pod # Base POD name
  namespace: boost-sales-system
spec:
  selector:
    matchLabels:
      app: boost-sales # Selector for POD name search.
  template:
    metadata:
      labels:
        app: boost-sales
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
      - name: boost-sales-api
        image: boost-sales-api
        ports:
        - name: boost-sales-api
          containerPort: 3000
        - name: boost-debug
          containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: boost-sales-service
  namespace: boost-sales-system
spec:
  type: ClusterIP
  selector:
    app: boost-sales
  ports:
  - name: boost-sales-api
    port: 3000
    targetPort: boost-sales-api
  - name: boost-debug
    port: 4000
    targetPort: boost-debug

