apiVersion: apps/v1
kind: Deployment
metadata:
  name: boost-sales-pod
  namespace: boost-sales-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: boost-sales
  template:
    metadata:
      labels:
        app: boost-sales
    spec:
      containers:
      # boost-sales-api container configuration
      - name: boost-sales-api
        resources:
          limits:
            cpu: "1000m" # Up to 2 full cores
          requests:
            cpu: "500m" # Use 1 full cores

