apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/boost-sales-pod/
images:
- name: boost-sales-api
  newName: bersennaidoo/boost-sales-api
  newTag: "1.0"
patches:
- path: ./kind-boost-sales-patch.yaml
