FROM golang:1.21-alpine AS build
ARG BUILD_REF

WORKDIR /src/

COPY . /src/

RUN CGO_ENABLED=0 go build -o /bin/service

FROM scratch

COPY --from=build /bin/service /bin/service

ENTRYPOINT ["/bin/service"]
